# Generated by Django 4.0.4 on 2022-05-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doorap_App', '0002_citymaster_countrymaster_myuser_login_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='created_datime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
