# Generated by Django 4.0.4 on 2022-05-06 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doorap_App', '0003_alter_myuser_created_datime'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendordetails',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
