# Generated by Django 4.0.4 on 2022-05-06 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doorap_App', '0004_vendordetails_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendordetails',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
    ]
