# Generated by Django 4.0.4 on 2022-05-06 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doorap_App', '0005_vendordetails_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='created_datime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
