# Generated by Django 4.0.4 on 2022-05-06 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doorap_App', '0006_alter_myuser_created_datime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='created_datime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
