# Generated by Django 4.0.4 on 2022-05-09 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doorap_App', '0008_venderaccountdetails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VenderAccountDetails',
            new_name='Vender_AccountDetails',
        ),
    ]
