# Generated by Django 4.0.4 on 2022-05-10 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doorap_App', '0009_rename_venderaccountdetails_vender_accountdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admindetails',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
