# Generated by Django 4.0.4 on 2022-05-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doorap_App', '0014_vendordetails_is_profile_create'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendordetails',
            name='is_profile_create',
        ),
        migrations.AddField(
            model_name='myuser',
            name='is_profile_create',
            field=models.BooleanField(default=False),
        ),
    ]
