# Generated by Django 4.0.4 on 2022-05-18 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Doorap_App', '0015_remove_vendordetails_is_profile_create_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, max_length=200, null=True)),
                ('category_image', models.FileField(blank=True, null=True, upload_to='VendorProfile/')),
                ('category_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.TextField(blank=True, null=True)),
                ('service_price', models.FloatField(blank=True, null=True)),
                ('service_time', models.IntegerField(blank=True, null=True)),
                ('service_status', models.BooleanField(default=False)),
                ('fk_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Doorap_App.categorymaster')),
            ],
        ),
    ]
