# Generated by Django 4.0.4 on 2022-05-19 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Doorap_App', '0016_categorymaster_servicemaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicemaster',
            name='service_image',
            field=models.FileField(blank=True, null=True, upload_to='VendorProfile/'),
        ),
        migrations.CreateModel(
            name='ServiceFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_name', models.TextField(blank=True, null=True)),
                ('facility_status', models.BooleanField(default=False)),
                ('fk_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Doorap_App.servicemaster')),
            ],
        ),
    ]
