# Generated by Django 4.0.4 on 2022-05-20 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Doorap_App', '0017_servicemaster_service_image_servicefacility'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenderCustomService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_service_image', models.FileField(blank=True, null=True, upload_to='VendorProfile/')),
                ('custom_service_name', models.TextField(blank=True, null=True)),
                ('custom_service_price', models.FloatField(blank=True, null=True)),
                ('custom_service_time', models.IntegerField(blank=True, null=True)),
                ('custom_service_status', models.BooleanField(default=False)),
                ('fk_vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Doorap_App.vendordetails')),
            ],
        ),
        migrations.CreateModel(
            name='VenderCustomFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_facility_name', models.TextField(blank=True, null=True)),
                ('custom_facility_status', models.BooleanField(default=False)),
                ('fk_custom_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Doorap_App.vendercustomservice')),
            ],
        ),
    ]
