# Generated by Django 4.0.4 on 2022-05-20 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Doorap_App', '0018_vendercustomservice_vendercustomfacility'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendercustomservice',
            name='fk_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Doorap_App.categorymaster'),
        ),
    ]
