# Generated by Django 4.0.4 on 2022-05-20 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Doorap_App', '0019_vendercustomservice_fk_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenderServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(blank=True, null=True)),
                ('hour', models.IntegerField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('fk_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Doorap_App.categorymaster')),
                ('fk_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Doorap_App.servicemaster')),
                ('fk_vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Doorap_App.vendordetails')),
            ],
        ),
        migrations.CreateModel(
            name='VenderFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vender_facility_status', models.BooleanField(default=False)),
                ('fk_vender_facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Doorap_App.servicefacility')),
                ('fk_vender_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Doorap_App.servicemaster')),
            ],
        ),
    ]
