# Generated by Django 4.0.4 on 2022-05-20 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Doorap_App', '0020_venderservices_venderfacility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venderfacility',
            name='fk_vender_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Doorap_App.venderservices'),
        ),
    ]
