# Generated by Django 4.0.4 on 2022-05-24 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Doorap_App', '0021_alter_venderfacility_fk_vender_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorSetSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_monday', models.BooleanField(default=False)),
                ('is_tuesday', models.BooleanField(default=False)),
                ('is_wednesday', models.BooleanField(default=False)),
                ('is_thursday', models.BooleanField(default=False)),
                ('is_friday', models.BooleanField(default=False)),
                ('is_saturday', models.BooleanField(default=False)),
                ('is_sunday', models.BooleanField(default=False)),
                ('from_date', models.TimeField(blank=True, null=True)),
                ('to_date', models.TimeField(blank=True, null=True)),
                ('fk_vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Doorap_App.vendordetails')),
            ],
        ),
    ]
