# Generated by Django 4.0.4 on 2022-05-24 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doorap_App', '0022_vendorsetschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venderservices',
            name='hour',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
