# Generated by Django 4.0.4 on 2022-05-24 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doorap_App', '0024_vendorsetschedule_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendordetails',
            name='from_date',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendordetails',
            name='is_friday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendordetails',
            name='is_monday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendordetails',
            name='is_saturday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendordetails',
            name='is_set_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendordetails',
            name='is_sunday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendordetails',
            name='is_thursday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendordetails',
            name='is_tuesday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendordetails',
            name='is_wednesday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendordetails',
            name='to_date',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='VendorSetSchedule',
        ),
    ]
