# Generated by Django 4.0.4 on 2022-05-26 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doorap_App', '0025_vendordetails_from_date_vendordetails_is_friday_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_title', models.CharField(blank=True, max_length=200, null=True)),
                ('banner_image', models.FileField(blank=True, null=True, upload_to='BannerImage/')),
                ('banner_status', models.BooleanField(default=False)),
            ],
        ),
    ]
