# Generated by Django 4.0.4 on 2022-05-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doorap_App', '0026_bannermaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendordetails',
            name='is_service_created',
            field=models.BooleanField(default=False),
        ),
    ]
