# Generated by Django 4.0.4 on 2022-05-28 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doorap_App', '0027_vendordetails_is_service_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendercustomservice',
            name='custom_service_time',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
