# Generated by Django 4.0.4 on 2022-05-28 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doorap_App', '0028_alter_vendercustomservice_custom_service_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicemaster',
            name='service_time',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
