# Generated by Django 4.0.4 on 2022-06-02 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doorap_App', '0030_addtocart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addtocart',
            name='item_total',
        ),
        migrations.RemoveField(
            model_name='addtocart',
            name='time',
        ),
        migrations.RemoveField(
            model_name='addtocart',
            name='total_amount',
        ),
    ]
