# Generated by Django 4.0.4 on 2022-06-02 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doorap_App', '0031_remove_addtocart_item_total_remove_addtocart_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtocart',
            name='cart_status',
            field=models.BooleanField(default=False),
        ),
    ]
