# Generated by Django 4.0.4 on 2022-06-03 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doorap_App', '0032_addtocart_cart_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtocart',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='addtocart',
            name='sub_total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
