# Generated by Django 4.0.4 on 2022-06-03 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doorap_App', '0033_addtocart_quantity_addtocart_sub_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addtocart',
            old_name='sub_total',
            new_name='price',
        ),
    ]
