# Generated by Django 4.0.4 on 2022-06-03 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doorap_App', '0034_rename_sub_total_addtocart_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtocart',
            name='sub_total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
