# Generated by Django 4.0.4 on 2022-06-03 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doorap_App', '0035_addtocart_sub_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtocart',
            name='hour',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
