# Generated by Django 4.0.4 on 2022-06-06 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doorap_App', '0038_commisionmaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtocart',
            name='convenience_fee',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
