# Generated by Django 4.0.4 on 2022-06-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doorap_App', '0040_orderdetails_orderservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='venderservices',
            name='rating',
            field=models.CharField(default='4', max_length=20),
        ),
    ]
