# Generated by Django 4.0.4 on 2022-06-13 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doorap_App', '0041_venderservices_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='promocode_applied_status',
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='user_promocode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
