# Generated by Django 4.0.4 on 2022-06-13 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Doorap_App', '0042_remove_orderdetails_promocode_applied_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='fk_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
