# Generated by Django 4.0.4 on 2022-06-16 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doorap_App', '0046_likedislike'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='vendor_pay_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
