# Generated by Django 4.0.4 on 2022-06-17 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doorap_App', '0049_alter_orderdetails_fk_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtocart',
            name='hour',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
