# Generated by Django 4.0.4 on 2022-06-21 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doorap_App', '0051_likedislike_fk_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='expirydate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offers',
            name='offercode_status',
            field=models.CharField(default='Active', max_length=50),
        ),
        migrations.AddField(
            model_name='offers',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
