# Generated by Django 4.0.4 on 2022-06-22 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doorap_App', '0053_offers_used_promocode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offers',
            old_name='used_promocode',
            new_name='used_offercode',
        ),
    ]
