# Generated by Django 4.0.4 on 2022-06-24 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doorap_App', '0054_rename_used_promocode_offers_used_offercode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendordetails',
            old_name='from_date',
            new_name='from_time',
        ),
        migrations.RenameField(
            model_name='vendordetails',
            old_name='to_date',
            new_name='to_time',
        ),
    ]
