# Generated by Django 4.0.4 on 2022-06-24 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doorap_App', '0055_rename_from_date_vendordetails_from_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vender_accountdetails',
            old_name='ifsc_code',
            new_name='BIC_code',
        ),
        migrations.RenameField(
            model_name='vender_accountdetails',
            old_name='account_holder_name',
            new_name='IBAN_no',
        ),
        migrations.AddField(
            model_name='vender_accountdetails',
            name='Bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
