# Generated by Django 4.0.4 on 2022-06-27 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doorap_App', '0056_rename_ifsc_code_vender_accountdetails_bic_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetails',
            old_name='fk_country',
            new_name='fk_city',
        ),
        migrations.RenameField(
            model_name='vender_accountdetails',
            old_name='account_no',
            new_name='Account_no',
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='booking_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
