# Generated by Django 4.0.4 on 2022-06-28 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doorap_App', '0059_addtocart_fk_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likedislike',
            name='fk_category',
        ),
    ]
