# Generated by Django 4.0.4 on 2022-07-01 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doorap_App', '0060_remove_likedislike_fk_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderservice',
            name='service_quantity',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
