# Generated by Django 4.0.4 on 2022-07-06 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doorap_App', '0061_orderservice_service_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderservice',
            name='hour',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
