# Generated by Django 4.0.4 on 2022-07-06 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doorap_App', '0062_orderservice_hour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addtocart',
            name='convenience_fee',
        ),
    ]
