# Generated by Django 4.0.4 on 2022-07-07 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Doorap_App', '0063_remove_addtocart_convenience_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='fk_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Doorap_App.categorymaster'),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='fk_country_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Doorap_App.countrymaster'),
        ),
    ]
