# Generated by Django 4.0.4 on 2022-07-09 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doorap_App', '0064_orderdetails_fk_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetails',
            old_name='city',
            new_name='customer_country',
        ),
    ]
