# Generated by Django 4.0.4 on 2022-07-11 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doorap_App', '0065_rename_city_orderdetails_customer_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
