# Generated by Django 4.0.4 on 2022-07-13 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doorap_App', '0066_alter_orderdetails_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='customer_city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
