# Generated by Django 4.0.4 on 2022-07-13 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doorap_App', '0068_notifications'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetails',
            old_name='booking_time',
            new_name='current_booking_time',
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='current_booking_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
