# Generated by Django 4.0.4 on 2022-07-14 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doorap_App', '0070_reviewsandfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='vendor_convenience_fee',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
