# Generated by Django 4.0.4 on 2022-07-14 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doorap_App', '0071_orderdetails_vendor_convenience_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendordetails',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
