# Generated by Django 4.0.4 on 2022-07-15 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doorap_App', '0072_alter_vendordetails_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewsandfeedback',
            name='is_feedback',
            field=models.BooleanField(default=True),
        ),
    ]
