# Generated by Django 4.0.4 on 2022-07-15 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doorap_App', '0073_alter_reviewsandfeedback_is_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewsandfeedback',
            name='review_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
