# Generated by Django 4.0.4 on 2022-07-18 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doorap_App', '0074_reviewsandfeedback_review_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='notification_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
