# Generated by Django 4.0.4 on 2022-07-19 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doorap_App', '0075_notifications_notification_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewsandfeedback',
            name='rating',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
