# Generated by Django 4.0.4 on 2022-07-21 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doorap_App', '0076_alter_reviewsandfeedback_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='payment_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='stripe_refund_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='stripe_refund_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='stripe_refund_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='stripe_txn_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='transjection_date',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='transjection_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
