# Generated by Django 4.0.4 on 2022-07-21 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doorap_App', '0077_orderdetails_payment_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetails',
            old_name='token',
            new_name='stripe_token',
        ),
    ]
