# Generated by Django 4.0.4 on 2022-07-22 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doorap_App', '0079_orderdetails_transjection_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='customer_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
