# Generated by Django 4.0.4 on 2022-07-23 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doorap_App', '0080_orderdetails_customer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetails',
            old_name='customer_id',
            new_name='payment_intent_id',
        ),
        migrations.AddField(
            model_name='myuser',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
