# Generated by Django 4.0.4 on 2022-08-02 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Doorap_App', '0082_rename_stripe_token_orderdetails_stripe_refund_txtid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='fk_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Doorap_App.orderdetails'),
        ),
    ]
