# Generated by Django 4.0.4 on 2022-08-02 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doorap_App', '0083_notifications_fk_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='user_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
