# Generated by Django 4.0.4 on 2022-08-03 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doorap_App', '0084_notifications_user_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='login_id',
            new_name='customer_login_id',
        ),
        migrations.RenameField(
            model_name='myuser',
            old_name='login_type',
            new_name='customer_login_type',
        ),
        migrations.AddField(
            model_name='myuser',
            name='vendor_login_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='vendor_login_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
