# Generated by Django 4.0.4 on 2022-08-04 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doorap_App', '0085_rename_login_id_myuser_customer_login_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='title_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
