# Generated by Django 4.0.4 on 2022-08-08 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doorap_App', '0086_notifications_title_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='login_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='login_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
