# Generated by Django 4.0.4 on 2022-08-23 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Doorap_App', '0087_myuser_login_id_myuser_login_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendordetails',
            name='vendor_earning',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendordetails',
            name='withdraw_request',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Vendor_Withdraw_Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_amount', models.FloatField(blank=True, null=True)),
                ('withdraw_status', models.CharField(default='Pending', max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('fk_vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Doorap_App.vendordetails')),
            ],
        ),
    ]
