# Generated by Django 4.0.4 on 2022-08-23 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doorap_App', '0088_vendordetails_vendor_earning_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendordetails',
            name='vendor_earning',
            field=models.FloatField(default=0),
        ),
    ]
