# Generated by Django 4.0.4 on 2022-08-23 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doorap_App', '0089_alter_vendordetails_vendor_earning'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendordetails',
            name='withdraw_request_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vendordetails',
            name='withdraw_request',
            field=models.FloatField(default=0),
        ),
    ]
