# Generated by Django 4.0.4 on 2022-08-23 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doorap_App', '0090_vendordetails_withdraw_request_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor_withdraw_payment',
            name='withdraw_request_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendordetails',
            name='withdraw_request_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
