# Generated by Django 4.0.4 on 2022-08-24 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doorap_App', '0091_vendor_withdraw_payment_withdraw_request_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor_withdraw_payment',
            name='payment_receive_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
