# Generated by Django 4.0.4 on 2023-01-27 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doorap_App', '0092_vendor_withdraw_payment_payment_receive_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendordetails',
            name='address_proof',
            field=models.FileField(blank=True, null=True, upload_to='VendorProfile/'),
        ),
        migrations.AddField(
            model_name='vendordetails',
            name='photo_id_proof',
            field=models.FileField(blank=True, null=True, upload_to='VendorProfile/'),
        ),
    ]
